{
 "title": "Energy consumption",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "price_per_kwh",
    "label": "Price per kWh (£)",
    "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: -7d)\r\n  |> filter(fn: (r) => r._measurement == \"p110_energy_price\" and r._field == \"price_per_kwh\")\r\n  |> last()\r\n  |> keep(columns: [\"_value\"])"
   },
   {
    "name": "standing_charge",
    "label": "Standing charge (£)",
    "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: -7d)\r\n  |> filter(fn: (r) => r._measurement == \"p110_energy_price\" and r._field == \"standing_charge\")\r\n  |> last()\r\n  |> keep(columns: [\"_value\"])"
   },
   {
    "name": "last_updated",
    "label": "Last updated",
    "query": "import \"strings\"\r\n\r\nfrom(bucket: v.defaultBucket)\r\n  |> range(start: -7d)\r\n  |> filter(fn: (r) => r._measurement == \"p110_energy_price\" and r._field == \"standing_charge\")\r\n  |> last()\r\n  |> map(fn: (r) => ({r with _value: strings.substring(end: 10, start: 0, v: string(v: r._time))}))\r\n  |> keep(columns: [\"_value\"])"
   },
   { "name": "exclude_kettle", "label": "Exclude kettle spikes", "query": "false, true" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "Any prices are calculated using the most recent price per kWh and standing charges from Ofgem using the default standard variable tariff. This price changes every quarter and so any longer term prices will use the latest values, meaning the actual cost may have been higher or lower."
   }
  },
  {
   "title": "Current draw (total)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "mwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tapo_p110_power_consumption_w",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: -10m)\r\n  |> filter(fn: (r) => r._measurement == \"p110_energy_consumption\" and r._field == \"current_power\")\r\n  |> last()\r\n  |> group(columns: [\"host\"])\r\n  |> sum()",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "room::tag", "operator": "=", "value": "kettle" }
     ]
    }
   ]
  },
  {
   "title": "Usage (today so far)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tapo_p110_power_consumption_w",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: -10m)\r\n  |> filter(fn: (r) => r._measurement == \"p110_energy_consumption\" and r._field == \"today_energy\")\r\n  |> last()\r\n  |> group(columns: [\"host\"])\r\n  |> sum()",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "room::tag", "operator": "=", "value": "kettle" }
     ]
    }
   ]
  },
  {
   "title": "Cost estimate (today so far)",
   "type": "stat",
   "description": "Including standard variable tariff standing charge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tapo_p110_power_consumption_w",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: -10m)\r\n  |> filter(fn: (r) => r._measurement == \"p110_energy_consumption\" and r._field == \"today_energy\")\r\n  |> last()\r\n  |> group(columns: [\"host\"])\r\n  |> sum()\r\n  |> map(fn: (r) => ({r with\r\n    _value: float(v: r._value / 1000) * ${price_per_kwh} + ${standing_charge}\r\n  }))",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "room::tag", "operator": "=", "value": "kettle" }
     ]
    }
   ]
  },
  {
   "title": "Usage (this month so far)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tapo_p110_power_consumption_w",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: -10m)\r\n  |> filter(fn: (r) => r._measurement == \"p110_energy_consumption\" and r._field == \"month_energy\")\r\n  |> last()\r\n  |> group(columns: [\"host\"])\r\n  |> sum()",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "room::tag", "operator": "=", "value": "kettle" }
     ]
    }
   ]
  },
  {
   "title": "Cost estimate (this month so far)",
   "type": "stat",
   "description": "Including standard variable tariff standing charge",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tapo_p110_power_consumption_w",
     "query": "import \"date\"\r\n\r\nfrom(bucket: v.defaultBucket)\r\n  |> range(start: -10m)\r\n  |> filter(fn: (r) => r._measurement == \"p110_energy_consumption\" and r._field == \"month_energy\")\r\n  |> last()\r\n  |> group(columns: [\"host\"])\r\n  |> sum()\r\n  |> map(fn: (r) => ({r with\r\n    _value: float(v: r._value / 1000) * ${price_per_kwh} + float(v: date.monthDay(t: now())) * ${standing_charge}\r\n  }))",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "room::tag", "operator": "=", "value": "kettle" }
     ]
    }
   ]
  },
  {
   "title": "Usage prediction (this month)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tapo_p110_power_consumption_w",
     "query": "import \"date\"\r\nimport \"math\"\r\n\r\ncur_date = now()\r\ncur_year = date.year(t: cur_date)\r\ncur_month = date.month(t: cur_date)\r\ncur_day = date.monthDay(t: cur_date)\r\nleap_year = if math.remainder(x: float(v: cur_year), y: 400.0) == 0.0 then\r\n  1\r\nelse if math.remainder(x: float(v: cur_year), y: 4.0) == 0.0 and math.remainder(x: float(v: cur_year), y: 100.0) != 0.0 then\r\n  1\r\nelse\r\n  0\r\ndays_in_month = if contains(value: cur_month, set: [4, 6, 9, 11]) then\r\n  30\r\nelse if contains(value: cur_month, set: [2,]) and leap_year == 0 then\r\n  28\r\nelse if contains(value: cur_month, set: [2,]) and leap_year == 1 then\r\n  29\r\nelse\r\n  31\r\n\r\nfrom(bucket: v.defaultBucket)\r\n  |> range(start: -10m)\r\n  |> filter(fn: (r) => r._measurement == \"p110_energy_consumption\" and r._field == \"month_energy\")\r\n  |> last()\r\n  |> group(columns: [\"host\"])\r\n  |> sum()\r\n  |> map(fn: (r) => ({r with\r\n    cur_year: cur_year,\r\n    leap_year: leap_year,\r\n    _value: float(v: (r._value / cur_day * days_in_month))\r\n  }))\r\n  |> keep(columns: [\"_value\"])",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "room::tag", "operator": "=", "value": "kettle" }
     ]
    }
   ]
  },
  {
   "title": "Cost prediction (this month)",
   "type": "stat",
   "description": "Including standard variable tariff standing charge, it takes the current kWh value, divides by the number of day in the month so far, then multiplies it by number of days in the month, calculating in price per kWh and standing charge.",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tapo_p110_power_consumption_w",
     "query": "import \"date\"\r\nimport \"math\"\r\n\r\ncur_date = now()\r\ncur_year = date.year(t: cur_date)\r\ncur_month = date.month(t: cur_date)\r\ncur_day = date.monthDay(t: cur_date)\r\nleap_year = if math.remainder(x: float(v: cur_year), y: 400.0) == 0.0 then\r\n  1\r\nelse if math.remainder(x: float(v: cur_year), y: 4.0) == 0.0 and math.remainder(x: float(v: cur_year), y: 100.0) != 0.0 then\r\n  1\r\nelse\r\n  0\r\ndays_in_month = if contains(value: cur_month, set: [4, 6, 9, 11]) then\r\n  30\r\nelse if contains(value: cur_month, set: [2,]) and leap_year == 0 then\r\n  28\r\nelse if contains(value: cur_month, set: [2,]) and leap_year == 1 then\r\n  29\r\nelse\r\n  31\r\n\r\nfrom(bucket: v.defaultBucket)\r\n  |> range(start: -10m)\r\n  |> filter(fn: (r) => r._measurement == \"p110_energy_consumption\" and r._field == \"month_energy\")\r\n  |> last()\r\n  |> group(columns: [\"host\"])\r\n  |> sum()\r\n  |> map(fn: (r) => ({r with\r\n    cur_year: cur_year,\r\n    leap_year: leap_year,\r\n    _value: (\r\n      float(v: ((r._value / 1000) / cur_day) * days_in_month) * ${price_per_kwh}\r\n    ) + (\r\n      float(v: days_in_month) * ${standing_charge}\r\n    )\r\n  }))\r\n  |> keep(columns: [\"_value\"])",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "room::tag", "operator": "=", "value": "kettle" }
     ]
    }
   ]
  },
  {
   "title": "Cost estimate for today so far (by device)",
   "type": "bargauge",
   "description": "Excluding standard variable tariff standing charge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: -10m)\r\n  |> filter(fn: (r) => r._measurement == \"p110_energy_consumption\" and r._field == \"today_energy\")\r\n  |> last()\r\n  |> map(fn: (r) => ({r with\r\n    _value: (float(v: r._value) / 1000.0) * ${price_per_kwh}\r\n  }))\r\n  |> map(fn: (r) => ({r with\r\n    _field: if r.name == \"pc\" then\r\n      \"PC\"\r\n    else if r.name == \"rack\" then\r\n      \"Rack\"\r\n    else if r.name == \"tv\" then\r\n      \"TV\"\r\n    else if r.name == \"kettle\" then\r\n      \"Kettle\"\r\n    else if r.name == \"fridge\" then\r\n      \"Fridge/Freezer\"\r\n    else if r.name == \"microwave\" then\r\n      \"Microwave\"\r\n    else if r.name == \"washing_machine\" then\r\n      \"Washing Machine\"\r\n    else if r.name == \"fan\" then\r\n      \"Fan\"\r\n    else if r.name == \"qi_charger\" then\r\n      \"Qi Charger\"\r\n    else if r.name == \"water_fountain\" then\r\n      \"Cat Water Fountain\"\r\n    else if r.name == \"alexa\" then\r\n      \"Alexa\"\r\n    else\r\n      r.name,\r\n  }))\r\n  |> keep(columns: [\"_time\", \"_field\", \"_value\"])\r\n  |> sort()"
    }
   ]
  },
  {
   "title": "Cost estimate for this month so far (by device)",
   "type": "bargauge",
   "description": "Excluding standard variable tariff standing charge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: -10m)\r\n  |> filter(fn: (r) => r._measurement == \"p110_energy_consumption\" and r._field == \"month_energy\")\r\n  |> last()\r\n  |> map(fn: (r) => ({r with\r\n    _value: (float(v: r._value) / 1000.0) * ${price_per_kwh}\r\n  }))\r\n  |> map(fn: (r) => ({r with\r\n    _field: if r.name == \"pc\" then\r\n      \"PC\"\r\n    else if r.name == \"rack\" then\r\n      \"Rack\"\r\n    else if r.name == \"tv\" then\r\n      \"TV\"\r\n    else if r.name == \"kettle\" then\r\n      \"Kettle\"\r\n    else if r.name == \"fridge\" then\r\n      \"Fridge/Freezer\"\r\n    else if r.name == \"microwave\" then\r\n      \"Microwave\"\r\n    else if r.name == \"washing_machine\" then\r\n      \"Washing Machine\"\r\n    else if r.name == \"fan\" then\r\n      \"Fan\"\r\n    else if r.name == \"qi_charger\" then\r\n      \"Qi Charger\"\r\n    else if r.name == \"water_fountain\" then\r\n      \"Cat Water Fountain\"\r\n    else if r.name == \"alexa\" then\r\n      \"Alexa\"\r\n    else\r\n      r.name,\r\n  }))\r\n  |> keep(columns: [\"_time\", \"_field\", \"_value\"])\r\n  |> sort()"
    }
   ]
  },
  {
   "title": "Cost estimate for today so far (by room)",
   "type": "bargauge",
   "description": "Excluding standard variable tariff standing charge",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: -10m)\r\n  |> filter(fn: (r) => r._measurement == \"p110_energy_consumption\" and r._field == \"today_energy\")\r\n  |> last()\r\n  |> map(fn: (r) => ({r with\r\n    _value: (float(v: r._value) / 1000.0) * ${price_per_kwh}\r\n  }))\r\n  |> map(fn: (r) =>  ({r with\r\n    _field: if r.room == \"kitchen\" then\r\n      \"Kitchen\"\r\n    else if r.room == \"office\" then\r\n      \"Office\"\r\n    else if r.room == \"living_room\" then\r\n      \"Living Room\"\r\n    else if r.room == \"bedroom\" then\r\n      \"Bedroom\"\r\n    else if r.room == \"hallway\" then\r\n      \"Hallway\"\r\n    else\r\n      r.room,\r\n  }))\r\n  |> group(columns: [\"_field\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\r\n  |> keep(columns: [\"_time\", \"_field\", \"_value\"])\r\n  |> sort()"
    }
   ]
  },
  {
   "title": "Cost estimate for this month so far (by rooom)",
   "type": "bargauge",
   "description": "Excluding standard variable tariff standing charge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: -10m)\r\n  |> filter(fn: (r) => r._measurement == \"p110_energy_consumption\" and r._field == \"month_energy\")\r\n  |> last()\r\n  |> map(fn: (r) => ({r with\r\n    _value: (float(v: r._value) / 1000.0) * ${price_per_kwh}\r\n  }))\r\n  |> map(fn: (r) =>  ({r with\r\n    _field: if r.room == \"kitchen\" then\r\n      \"Kitchen\"\r\n    else if r.room == \"office\" then\r\n      \"Office\"\r\n    else if r.room == \"living_room\" then\r\n      \"Living Room\"\r\n    else if r.room == \"bedroom\" then\r\n      \"Bedroom\"\r\n    else if r.room == \"hallway\" then\r\n      \"Hallway\"\r\n    else\r\n      r.room,\r\n  }))\r\n  |> group(columns: [\"_field\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\r\n  |> keep(columns: [\"_time\", \"_field\", \"_value\"])\r\n  |> sort()"
    }
   ]
  },
  {
   "title": "Current draw (total)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "mwatt" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tapo_p110_power_consumption_w",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"p110_energy_consumption\")\r\n  |> filter(fn: (r) => if \"${exclude_kettle}\" == \"true\" then r._field == \"current_power\" and r.name != \"kettle\" else r._field == \"current_power\")\r\n  |> group(columns: [\"_time\"], mode:\"by\")\r\n  |> sum(column: \"_value\")\r\n  |> group()\r\n  |> fill(value: 0)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\r\n  |> keep(columns: [\"_time\", \"_value\"])",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "room::tag", "operator": "=", "value": "kettle" }
     ]
    }
   ]
  },
  {
   "title": "Usage (year)",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "query": "import \"strings\"\r\n\r\nfrom(bucket: v.defaultBucket)\r\n  |> range(start: -1y)\r\n  |> filter(fn: (r) => r._measurement == \"p110_energy_monthly_total\" and r._field == \"total_sum\")\r\n  |> group(columns: [\"host\"])\r\n  |> aggregateWindow(every: 1mo, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({r with\r\n    _time: strings.substring(end: 7, start: 0, v: string(v: r._time))\r\n  }))\r\n  |> keep(columns: [\"_time\", \"_value\"])"
    }
   ]
  },
  {
   "title": "Cost (year)",
   "type": "barchart",
   "description": "Estimated. Using the current price per kWh and standing charges, so months outside of the current price cap which is set per quarter may have been higher or lower",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "targets": [
    {
     "query": "import \"date\"\r\nimport \"math\"\r\nimport \"strings\"\r\n\r\ncur_date = now()\r\ncur_year = date.year(t: cur_date)\r\ncur_month = date.month(t: cur_date)\r\ncur_day = date.monthDay(t: cur_date)\r\nleap_year = if math.remainder(x: float(v: cur_year), y: 400.0) == 0.0 then\r\n  1\r\nelse if math.remainder(x: float(v: cur_year), y: 4.0) == 0.0 and math.remainder(x: float(v: cur_year), y: 100.0) != 0.0 then\r\n  1\r\nelse\r\n  0\r\ndays_in_month = if contains(value: cur_month, set: [4, 6, 9, 11]) then\r\n  30\r\nelse if contains(value: cur_month, set: [2,]) and leap_year == 0 then\r\n  28\r\nelse if contains(value: cur_month, set: [2,]) and leap_year == 1 then\r\n  29\r\nelse\r\n  31\r\n\r\nfrom(bucket: v.defaultBucket)\r\n  |> range(start: -1y)\r\n  |> filter(fn: (r) => r._measurement == \"p110_energy_monthly_total\" and r._field == \"total_sum\")\r\n  |> group(columns: [\"host\"])\r\n  |> aggregateWindow(every: 1mo, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({r with\r\n    _time: strings.substring(end: 7, start: 0, v: string(v: r._time)),\r\n    _value: (\r\n      float(v: ((r._value / 1000) / cur_day) * days_in_month) * ${price_per_kwh}\r\n    ) + (\r\n      float(v: days_in_month) * ${standing_charge}\r\n    )\r\n  }))\r\n  |> keep(columns: [\"_time\", \"_value\"])"
    }
   ]
  },
  {
   "title": "Current draw (by device)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "mwatt" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tapo_p110_power_consumption_w",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"p110_energy_consumption\")\r\n  |> filter(fn: (r) => if \"${exclude_kettle}\" == \"true\" then r._field == \"current_power\" and r.name != \"kettle\" else r._field == \"current_power\")\r\n  |> fill(value: 0)\r\n  |> map(fn: (r) => ({r with\r\n    _field: if r.name == \"pc\" then\r\n      \"PC\"\r\n    else if r.name == \"rack\" then\r\n      \"Rack\"\r\n    else if r.name == \"tv\" then\r\n      \"TV\"\r\n    else if r.name == \"kettle\" then\r\n      \"Kettle\"\r\n    else if r.name == \"fridge\" then\r\n      \"Fridge/Freezer\"\r\n    else if r.name == \"microwave\" then\r\n      \"Microwave\"\r\n    else if r.name == \"washing_machine\" then\r\n      \"Washing Machine\"\r\n    else if r.name == \"fan\" then\r\n      \"Fan\"\r\n    else if r.name == \"qi_charger\" then\r\n      \"Qi Charger\"\r\n    else if r.name == \"water_fountain\" then\r\n      \"Cat Water Fountain\"\r\n    else if r.name == \"alexa\" then\r\n      \"Alexa\"\r\n    else\r\n      r.name,\r\n  }))\r\n  |> keep(columns: [\"_time\", \"_field\", \"_value\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "room::tag", "operator": "=", "value": "kettle" }
     ]
    }
   ]
  },
  {
   "title": "Current draw (by room)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "mwatt" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tapo_p110_power_consumption_w",
     "query": "import \"math\"\r\n\r\ntelegraf_send_freq = 10\r\ninterval_seconds = int(v: math.mMax(x: float(v: $__interval_ms) / 1000.0, y: float(v: telegraf_send_freq)))\r\nwindow_period = duration(v: string(v: interval_seconds) + \"s\")\r\n\r\nfrom(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"p110_energy_consumption\")\r\n  |> filter(fn: (r) => if \"${exclude_kettle}\" == \"true\" then r._field == \"current_power\" and r.name != \"kettle\" else r._field == \"current_power\")\r\n  |> fill(value: 0)\r\n  |> keep(columns: [\"_time\", \"_field\", \"_value\", \"room\"])\r\n  |> group(columns: [\"room\"])\r\n  |> aggregateWindow(every: window_period, fn: sum)\r\n  |> map(fn: (r) =>  ({r with\r\n    room: if r.room == \"kitchen\" then\r\n      \"Kitchen\"\r\n    else if r.room == \"office\" then\r\n      \"Office\"\r\n    else if r.room == \"living_room\" then\r\n      \"Living Room\"\r\n    else if r.room == \"bedroom\" then\r\n      \"Bedroom\"\r\n    else if r.room == \"hallway\" then\r\n      \"Hallway\"\r\n    else\r\n      r.room,\r\n    _value: r._value / (interval_seconds / telegraf_send_freq),\r\n  }))",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "room::tag", "operator": "=", "value": "kettle" }
     ]
    }
   ]
  }
 ]
}